"""empty message

Revision ID: 36020a7fe1cb
Revises: 210be4862f1e
Create Date: 2022-04-24 10:53:25.261857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36020a7fe1cb'
down_revision = '210be4862f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('Song', sa.Column('artist', sa.String(length=255), nullable=True))
    op.add_column('Song', sa.Column('album_name', sa.String(length=255), nullable=True))
    op.add_column('Song', sa.Column('album_thumb', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Song', 'artist')
    op.drop_column('Song', 'album_name')
    op.drop_column('Song', 'album_thumb')
    # ### end Alembic commands ###
