"""empty message

Revision ID: 45f2824da51a
Revises: 36020a7fe1cb
Create Date: 2022-04-26 10:44:06.085682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45f2824da51a'
down_revision = '36020a7fe1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locationsong', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('locationsong', sa.Column('updated_at', sa.DateTime(), nullable=True))
    print("Add column locationsong")
    op.add_column('locationsong', sa.Column('song_local_popularity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locationsong', 'created_on')
    op.drop_column('locationsong', 'updated_at')
    op.drop_column('locationsong', 'song_local_popularity')

    # ### end Alembic commands ###
